# Generated by Django 2.1.2 on 2019-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'low'), ('normal', 'normal'), ('high', 'high')], default='normal', max_length=100)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
    ]
